kind: Deployment
apiVersion: apps/v1
metadata:
   name: backend-deployment
   namespace: backend
spec:
   replicas: 2
   selector:
       matchLabels:
           - name: backend-deployment
   template:
      metadata:
          name: backend-deployment
          labels: 
            - name: backend-deployment
      spec: 
         containers:
              - name: backendpod
                image: bhasmeht/bookstorebackend # {"$imagepolicy": "flux-system:backend-podinfo"}
                ports:
                  - containerPort: 4000               