kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-deployment
  template:
    metadata:
      name: backend-deployment
      labels:
        name: backend-deployment
    spec:
      containers:
        - name: backendpod
          # image: bhasmeht/bookstorebackend:1.1.6 # {"$imagepolicy": "flux-system:backend-podinfo"}
          image: bhasmeht/bookstorebackend:1.1.6
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: backend-config
