kind: Service
apiVersion: v1 
metadata:
   name: backend-svc 
spec:
   selector:
        - name:backend-deployment  
   ports:
      - protocol: "TCP"
        port: 4000
        targetPort: 4000     
        